apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-tskx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-tskx
    app.kubernetes.io/part-of: test-annotations-app-dxre
  name: test-annotations-tskx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-tskx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-tskx
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-chgj-tenant/test-annotations-app-dxre/test-annotations-tskx@sha256:2b7c743851811ef2f43cbaa02497fc9466b4fbd09523c25e81baf66aef150aeb
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
